/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.Myconnection;
import DAO.HoaTuoiDAO;
import entities.HoaTuoi;
import entities.loginuser;
import helper.DateHelper;
import helper.DialogHelper;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguye
 */
public class HoaTuoiUI extends javax.swing.JFrame {

    String fileimage = "";
    public static String admin = "";

    public void fillcbboxmaloaihoa() {
        new HoaTuoiDAO().fillcbboxmaloaihoa(cbomaloaihoa);
    }

    public void showList() {
        new HoaTuoiDAO().showDetail(tblbang);
    }

    public void chonHinh() {
        fileimage = new HoaTuoiDAO().chonAnh(lbllogo);
    }

    public void insertItem() {
        HoaTuoi ht = new HoaTuoi(txtMahoatuoi.getText(), txtTenhoa.getText(),
                cbomaloaihoa.getSelectedItem().toString(),
                Integer.parseInt(txtSoluong.getText()), Integer.parseInt(txtDongia.getText()),
                fileimage, txtGhichu.getText());
        new HoaTuoiDAO().them(ht);
    }

    public void updateItem() {
        HoaTuoi ht = new HoaTuoi(txtMahoatuoi.getText(), txtTenhoa.getText(),
                cbomaloaihoa.getSelectedItem().toString(),
                Integer.parseInt(txtSoluong.getText()), Integer.parseInt(txtDongia.getText()),
                fileimage, txtGhichu.getText());
        new HoaTuoiDAO().sua(ht);
    }

    public void showDetail() throws IOException {
        HoaTuoi ht = new HoaTuoiDAO().hienthi(tblbang);
        txtMahoatuoi.setText(ht.getMaHoaTuoi());
        txtTenhoa.setText(ht.getTenHoaTuoi());
        cbomaloaihoa.setSelectedItem(ht.getMaLoaiHoa());
        txtDongia.setText(String.valueOf(ht.getDonGia()));
        txtSoluong.setText(String.valueOf(ht.getSoLuong()));
        txtGhichu.setText(String.valueOf(ht.getGhiChu()));
        fileimage = ht.getHinh();
        BufferedImage img = ImageIO.read(new File("src\\hoadathem\\" + fileimage));
        Image dmg = img.getScaledInstance(lbllogo.getWidth(), lbllogo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(dmg);
        lbllogo.setIcon(icon);
    }

    public void deleteItem() {
        int r = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa không?");
        if (r == JOptionPane.YES_OPTION) {
            HoaTuoi ht = new HoaTuoi(txtMahoatuoi.getText(), txtTenhoa.getText(),
                    cbomaloaihoa.getSelectedItem().toString(),
                    Integer.parseInt(txtSoluong.getText()), Integer.parseInt(txtDongia.getText()),
                    fileimage, txtGhichu.getText());
            new HoaTuoiDAO().xoa(ht);
        }
    }

    public boolean Check() {
        if (txtMahoatuoi.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa Nhập Mã Hoa Tươi");
            txtMahoatuoi.requestFocus();
            return false;
        } else if (txtTenhoa.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa Nhập Tên Hoa");
            txtTenhoa.requestFocus();
            return false;
        } else if (cbomaloaihoa.getSelectedItem().toString().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa chọn Mã Loại Hoa");
            cbomaloaihoa.requestFocus();
            return false;
        } else if (txtSoluong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa Nhập Số Lượng");
            txtSoluong.requestFocus();
            return false;
        } else if (txtDongia.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa Nhập Đơn Giá");
            txtDongia.requestFocus();
            return false;
        }
        return true;
    }

    public HoaTuoiUI() {
        initComponents();
        getContentPane().setBackground(new Color(243, 194, 70));
        setLocationRelativeTo(this);
        showList();

        fillcbboxmaloaihoa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbang = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMahoatuoi = new javax.swing.JTextField();
        txtTenhoa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDongia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhichu = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btntimkiem = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtSoluong = new javax.swing.JTextField();
        lbllogo = new javax.swing.JLabel();
        cbomaloaihoa = new javax.swing.JComboBox<>();
        txttimkiem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SHOP HOA TƯƠI THE KINGDOM OF FLOWER");
        setBackground(new java.awt.Color(255, 0, 51));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icon/hoa24.png")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ HOA");

        tblbang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblbang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hoa tươi", "Tên hoa", "Mã loại hoa", "Đơn giá", "Số lượng", "Ghi chú"
            }
        ));
        tblbang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbang);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mã hoa tươi:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tên Hoa:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Đơn giá:");

        txtMahoatuoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTenhoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Mã loại hoa:");

        txtDongia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Ghi chú:");

        txtGhichu.setColumns(20);
        txtGhichu.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtGhichu.setRows(5);
        jScrollPane2.setViewportView(txtGhichu);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Tìm kiếm:");

        btntimkiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        btntimkiem.setText("Tìm ");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnsua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Notes.png"))); // NOI18N
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Text.png"))); // NOI18N
        jButton4.setText("Mới");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Số lượng:");

        txtSoluong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbllogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogo.setBorder(javax.swing.BorderFactory.createTitledBorder("Hình Ảnh"));
        lbllogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllogoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMahoatuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel6)
                                .addGap(26, 26, 26)
                                .addComponent(cbomaloaihoa, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDongia, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttimkiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btntimkiem))
                    .addComponent(jScrollPane1))
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnThem)
                .addGap(84, 84, 84)
                .addComponent(btnsua)
                .addGap(87, 87, 87)
                .addComponent(btnXoa)
                .addGap(72, 72, 72)
                .addComponent(jButton4)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btntimkiem)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtMahoatuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(cbomaloaihoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtTenhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtDongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel7))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(btnsua)
                    .addComponent(btnThem)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (admin.equals("administrator")) {
            if (Check() == true) {
                insertItem();
            }
            showList();
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không phải chủ shop!");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed

        if (admin.equals("administrator")) {
            if (checkma()) {
                deleteItem();
            }
            showList();
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không phải chủ shop!");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        if (admin.equals("administrator")) {
            if (Check() == true) {
                HoaTuoi ht = new HoaTuoi();
                ht.setMaHoaTuoi(txtMahoatuoi.getText());
                ht.setTenHoaTuoi(txtTenhoa.getText());
                ht.setMaLoaiHoa(cbomaloaihoa.getSelectedItem().toString());
                ht.setSoLuong(Integer.parseInt(txtSoluong.getText()));
                ht.setDonGia(Integer.parseInt(txtDongia.getText()));
                ht.setHinh(fileimage);
                ht.setGhiChu(txtGhichu.getText());

                HoaTuoiDAO htd = new HoaTuoiDAO();
                int kq = htd.sua(ht);
                if (kq == 1) {

                } else if (kq == 0) {
                    JOptionPane.showMessageDialog(this, "Update that bai!");
                } else if (kq == -1) {
                    JOptionPane.showMessageDialog(this, "Khong ket noi duoc voi database!");
                }
            }
            showList();
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không phải chủ shop!");
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void tblbangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbangMouseClicked
        try {
            showDetail();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblbangMouseClicked

    private void lbllogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoMouseClicked
        chonHinh();
    }//GEN-LAST:event_lbllogoMouseClicked

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
        new HoaTuoiDAO().searchHoaTuoi(tblbang, txttimkiem.getText());
    }//GEN-LAST:event_btntimkiemActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        txtDongia.setText("");
        txtGhichu.setText("");
        txtMahoatuoi.setText("");
        txtSoluong.setText("");
        txtTenhoa.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        user();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaTuoiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaTuoiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaTuoiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaTuoiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaTuoiUI().setVisible(true);
            }
        });
    }

    public boolean checkma() {
        if (txtMahoatuoi.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã hoa tươi!");
            txtMahoatuoi.requestFocus();
            return false;
        }
        return true;
    }

    public static void user() {
        loginuser lg = new loginuser();
        admin = lg.getUsername();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JComboBox<String> cbomaloaihoa;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JTable tblbang;
    private javax.swing.JTextField txtDongia;
    private javax.swing.JTextArea txtGhichu;
    private javax.swing.JTextField txtMahoatuoi;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTenhoa;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables

}
