/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.NhanVienDao;
import entities.NhanVien;
import entities.loginuser;
import helper.DateHelper;
import helper.ShareHelper;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Diem Ngon Trai
 */
public class NhanVienUI extends javax.swing.JFrame {

    public static String admin = "";
    String fileimage = "";

    public NhanVienUI() {
        initComponents();
        getContentPane().setBackground(new Color(243, 194, 70));
        setLocationRelativeTo(this);
        init();

        showList();
    }

    public static void user() {
        loginuser lg = new loginuser();
        admin = lg.getUsername();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lbllogo = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbang = new javax.swing.JTable();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDiemThoai = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cboGioiTinh = new javax.swing.JComboBox<>();
        txtluong = new javax.swing.JTextField();
        btnThanhToanLuong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SHOP HOA TƯƠI THE KINGDOM OF FLOWER");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icon/hoa24.png")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Điện Thoại:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Giới Tính:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Quản Lý Nhân Viên");

        txtMaNV.setEditable(false);
        txtMaNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        lbllogo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lbllogoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        lbllogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllogoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbllogo, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbllogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtTenNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tblbang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Ngày Sinh", "Giới Tính", "Địa Chỉ", "Điện Thoại", "Hình"
            }
        ));
        tblbang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbang);
        if (tblbang.getColumnModel().getColumnCount() > 0) {
            tblbang.getColumnModel().getColumn(2).setResizable(false);
            tblbang.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
        );

        txtNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNgaySinh.setText("10-10-2000");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mã Nhân Viên:");

        txtDiemThoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tên Nhân Viên:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Địa Chỉ:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Ngày Sinh:");

        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnThem.setBackground(new java.awt.Color(0, 153, 204));
        btnThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnThem.setText("Thêm ");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 102, 0));
        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnxoa.setBackground(new java.awt.Color(255, 0, 0));
        btnxoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnxoa.setForeground(new java.awt.Color(255, 255, 255));
        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Notes.png"))); // NOI18N
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(0, 204, 0));
        btnLamMoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Document.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 153, 204));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Lương:");

        cboGioiTinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", " " }));

        txtluong.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtluong.setText("0");

        btnThanhToanLuong.setBackground(new java.awt.Color(0, 153, 153));
        btnThanhToanLuong.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnThanhToanLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Dollar.png"))); // NOI18N
        btnThanhToanLuong.setText("Thanh Toán Lương");
        btnThanhToanLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanLuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(409, 409, 409)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnxoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLamMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThanhToanLuong)
                        .addGap(86, 86, 86)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtluong))
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi)
                    .addComponent(btnxoa)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(txtluong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThanhToanLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (admin.equals("administrator")) {
            if (Check()) {
                this.updateItem();
            }
            showList();
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không phải chủ shop!");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (admin.equals("administrator")) {
            if (Check()) {
                this.insertItem();
            }
            showList();
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không phải chủ shop!");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        lbllogo.setIcon(null);
        txtMaNV.setText("");
        txtDiemThoai.setText("");
        txtDiaChi.setText("");
        txtNgaySinh.setText("00-00-2000");
        txtluong.setText("0");
        cboGioiTinh.setSelectedIndex(0);
        txtTenNV.setText("");
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        if (admin.equals("administrator")) {
            if (CheckDelete()) {
                this.deleteItem();
            }
            showList();
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không phải chủ shop!");
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void tblbangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbangMouseClicked
        try {
            showDetail();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblbangMouseClicked

    private void lbllogoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lbllogoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lbllogoAncestorAdded

    private void lbllogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoMouseClicked
        chonHinh();
    }//GEN-LAST:event_lbllogoMouseClicked

    private void btnThanhToanLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanLuongActionPerformed
        if (admin.equals("administrator")) {
            thanhtoanluong();
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không phải chủ shop!");
        }
    }//GEN-LAST:event_btnThanhToanLuongActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        user();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new NhanVienUI().setVisible(true);

            }
        });
    }

    public void chonHinh() {
        fileimage = new NhanVienDao().chonAnh(lbllogo);
    }

    public void showList() {
        new NhanVienDao().showDetail(tblbang);
    }

    public void showDetail() throws IOException {
        NhanVien cd = new NhanVienDao().hienthi(tblbang);
        txtMaNV.setText(String.valueOf(cd.getMaNV()));
        txtTenNV.setText(cd.getTenNV());
        txtNgaySinh.setText(String.valueOf(cd.getNgaysinh2()));
        cboGioiTinh.setSelectedIndex(Integer.valueOf(cd.getGioiTinh()));
        txtDiaChi.setText(String.valueOf(cd.getDiaChi()));
        txtDiemThoai.setText(String.valueOf(cd.getDienThoai()));
        fileimage = cd.getHinh();
        txtluong.setText(String.valueOf(cd.getLuong()));
        BufferedImage img = ImageIO.read(new File("src\\NhanVien\\" + fileimage));
        Image dmg = img.getScaledInstance(lbllogo.getWidth(), lbllogo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(dmg);
        lbllogo.setIcon(icon);
    }

    public void insertItem() {

        NhanVien nv = new NhanVien();
        nv.setTenNV(txtTenNV.getText());
        nv.setNgaySinh(DateHelper.toDate(txtNgaySinh.getText()));
        if (cboGioiTinh.getSelectedItem() == "Nam") {
            nv.setGioiTinh(0);
        } else {
            nv.setGioiTinh(1);
        }
        nv.setDiaChi(txtDiaChi.getText());
        nv.setDienThoai(txtDiemThoai.getText());
        nv.setHinh(fileimage);
        nv.setLuong(Integer.parseInt(txtluong.getText()));

        NhanVienDao nvd = new NhanVienDao();
        int kq = nvd.insertItem(nv);
        if (kq == 1) {
            JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công!");
        } else if (kq == -1) {
            JOptionPane.showMessageDialog(this, "Kết nối với database thất bại!");
        } else if (kq == 0) {
            JOptionPane.showMessageDialog(this, "Sai định dạng! Hãy kiểm tra lại bạn đã nhập đúng chưa!");
        }

    }

    public void updateItem() {
        NhanVien nv = new NhanVien();
        nv.setMaNV(Integer.parseInt(txtMaNV.getText()));
        nv.setTenNV(txtTenNV.getText());
        nv.setNgaySinh(DateHelper.toDate(txtNgaySinh.getText()));
        if (cboGioiTinh.getSelectedItem() == "Nam") {
            nv.setGioiTinh(0);
        } else {
            nv.setGioiTinh(1);
        }
        nv.setDiaChi(txtDiaChi.getText());
        nv.setDienThoai(txtDiemThoai.getText());
        nv.setHinh(fileimage);
        nv.setLuong(Integer.parseInt(txtluong.getText()));

        NhanVienDao nvd = new NhanVienDao();
        int kq = nvd.updateItem(nv);
        if (kq == 1) {
            JOptionPane.showMessageDialog(this, "Sửa Nhân viên thành công!");
        } else if (kq == -1) {
            JOptionPane.showMessageDialog(this, "Kết nối với database thất bại!");
        } else if (kq == 0) {
            JOptionPane.showMessageDialog(this, "Sai định dạng! Hãy kiểm tra lại bạn đã nhập đúng chưa!");
        }
    }

    public void deleteItem() {
        NhanVien nv = new NhanVien();
        nv.setMaNV(Integer.valueOf(txtMaNV.getText()));
        nv.setTenNV(txtTenNV.getText());
        nv.setNgaySinh(DateHelper.toDate(txtNgaySinh.getText()));
        if (cboGioiTinh.getSelectedItem() == "Nam") {
            nv.setGioiTinh(0);
        } else {
            nv.setGioiTinh(1);
        }
        nv.setDiaChi(txtDiaChi.getText());
        nv.setDienThoai(txtDiemThoai.getText());
        nv.setHinh(fileimage);

        NhanVienDao nvd = new NhanVienDao();
        int kq = nvd.deleteItem(nv);
        if (kq == 1) {
            JOptionPane.showMessageDialog(this, "Đã xóa Nhân Viên!");
        } else if (kq == -1) {
            JOptionPane.showMessageDialog(this, "Kết nối với database không thành công!");
        } else if (kq == 0) {
            JOptionPane.showMessageDialog(this, "Sai định dạng! Hãy kiểm tra lại bạn đã nhập đúng chưai!");
        }
    }

    public boolean Check() {
        if (txtTenNV.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Hãy nhập tên Nhân Viên!");
            txtTenNV.requestFocus();
            return false;
        } else if (txtNgaySinh.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Hãy nhập Ngày Sinh của Nhân Viên!");
            txtNgaySinh.requestFocus();
            return false;
        } else if (!txtNgaySinh.getText().matches("\\d{1,2}-\\d{1,2}-\\d{4}")) {
            JOptionPane.showMessageDialog(this, "Định dạng Ngày Sinh không chính xác! phải là dd-mm-yyyy");
            txtNgaySinh.requestFocus();
            return false;
        } else if (txtDiemThoai.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Hãy nhập Số Điện Thoại của Nhân Viên!");
            txtDiemThoai.requestFocus();
            return false;
        } else if (!txtDiemThoai.getText().matches("[0-9]{10}")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại phải là 10 chữ số!");
            txtDiemThoai.requestFocus();
            return false;
        } else if (txtluong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Hãy nhập lương cho nhân viên!");
            txtluong.requestFocus();
            return false;
        } else if (txtluong.getText().matches("\\d{8}")) {
            JOptionPane.showMessageDialog(this, "Lương phải nhập bằng số và không được quá 7 số!");
            txtluong.requestFocus();
            return false;
        }
        return true;
    }

    public boolean CheckDelete() {
        if (txtMaNV.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Hãy chọn Nhân Viên muốn Delete để hiện mã Nhân Viên!");
            return false;
        }
        return true;
    }

    public void thanhtoanluong() {
        NhanVien nv = new NhanVien();
        String manv = txtMaNV.getText() + "\n";
        String TenNV = txtTenNV.getText() + "\n";
        String NgaySinh = txtNgaySinh.getText() + "\n";
        String DiemThoai = txtDiemThoai.getText() + "\n";
        String DiaChi = txtDiaChi.getText() + "\n";
        String Luong = txtluong.getText() + "\n";
        nv.setMaNV(Integer.parseInt(txtMaNV.getText()));
        NhanVienDao nvd = new NhanVienDao();
        int kq = nvd.resetluong(nv);
        if (kq == 1) {
            JOptionPane.showMessageDialog(this, "Mã nhân viên: \t\t " + manv + "Họ Tên: \t\t" + TenNV + "Ngày sinh: \t\t" + NgaySinh + "Số điện thoại: \t\t" + DiemThoai + "Địa chỉ: \t\t" + DiaChi + "Lương: \t\t" + Luong + "\n");
        } else {
            JOptionPane.showMessageDialog(null, "Mã nhân viên chưa hiện lên để có thể xóa!");
        }
        showList();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThanhToanLuong;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnxoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboGioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JTable tblbang;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDiemThoai;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtluong;
    // End of variables declaration//GEN-END:variables
    int index = 0;
    NhanVienDao dao = new NhanVienDao();

    void init() {
        setIconImage(ShareHelper.APP_ICON);
        setLocationRelativeTo(null);
    }

//    void setModel(NhanVien model){
//        txtMaNV.setText(model.getMaNV());
//        txtTenNV.setText(model.getTenNV());
//        txtNgaySinh.setText(DateHelper.toString(model.getNgaySinh()));        
//        cboGioiTinh.setSelectedIndex(model.getGioiTinh()?0:1);
//        txtDiaChi.setText(model.getDiaChi());
//        txtDiemThoai.setText(model.getDienThoai());
//        lbllogo.setText(model.getHinh());
//    }
//
//    NhanVien getModel() {
//        NhanVien model = new NhanVien();
//        model.setMaNV(Integer.parseInt(txtMaNV.getText()));
//        model.setTenNV(txtTenNV.getText());
//        model.setNgaySinh(DateHelper.toDate(txtNgaySinh.getText()));
//        NhanVien chuyenDe = (ChuyenDe) cboChuyenDe.getSelectedItem();
//        model.setDiaChi(txtDiaChi.getText());
//        model.setDienThoai(txtDiemThoai.getText());
//        return model;
//    }
//        
//    void setStatus(boolean insertable){
//        txtMaNV.setEditable(insertable);
//        btnThem.setEnabled(insertable);
//        btnSua.setEnabled(!insertable);
//        btnxoa.setEnabled(!insertable);
//        boolean first = this.index > 0;
//        boolean last = this.index < tblbang.getRowCount() - 1;
//        btnFirst.setEnabled(!insertable && first);
//        btnPrev.setEnabled(!insertable && first);
//        btnLast.setEnabled(!insertable && last);
//        btnNext.setEnabled(!insertable && last);
}
